Optionally use material search
backstage/mkdocs-techdocs-core pull request #202
Opened 2024-07-02 11:00 UTC by alexef

fixes: #192 

see also: https://github.com/backstage/backstage/pull/25497

the `search/search_index.json` template behaves differently based on which search plugin is being used.

with this change, we allow users to use material theme's search for generating the index.

Differences:

||Mkdocs search|Material theme search|
|---|---|---|
|Document split|Both entire document and heading sections|Only headings|
|Content escaping|Yes, both title and text|No, only titles. Text still contains html tags|
|Tags support|No|Yes|
|Boost support|No|Yes|

2024-07-02 12:37 UTC, alexef commented
(validated this works as expected in https://github.com/alexef/mkdocs-techdocs-core/blob/dev/src/core.py#L22, but I'm yet to validate that using custom settings like the proposed way in this PR will work)

2024-07-02 12:37 UTC, awanlin requested changes
Thanks for taking this on @alexef, left one comment.

I'm also wondering, would this impact the core Backstage Search feature? Would you be able to test that to confirm?

2024-07-02 12:37 UTC, awanlin commented on src/core.py
> +        use_material_search = config["plugins"]["techdocs-core"].get("material_search", False)
Can we document this somewhere? The `README` would be fine for now.

2024-07-02 14:08 UTC, alexef commented
We are using it locally and search seems to work just like before (except that now we don't get duplicate results). 

Updated README added a tiny unit test.  If you can please have another look.

2024-07-02 18:25 UTC, awanlin requested changes
Small typo, other changes look good though 👍

2024-07-03 12:17 UTC, awanlin approved these changes
Thanks again @alexef 🚀 

I'm the initial review but we need the TechDocs team to look as well so I'll pull them in. It might take a bit longer as it's a holiday tomorrow in the US.

2024-07-05 13:46 UTC, byan1197 approved these changes
Looks great, thank you for your contribution!

2024-07-09 14:33 UTC, tcardonne commented
Hello 👋 

First of all thanks for the PR! We also have the need to boost individual pages in a TechDocs but we didn't implement this yet.

We tried using the `material-mkdocs` search plugin on our side and we had some issue with it.
I'm curious on how you managed to get around these.
With this PR, enabling the flag will result in Backstage search results containing raw HTML tags.

The text contains html tags (like `<p>` and `<code>`) which are used for [rich text previews on Mkdocs Material](https://squidfunk.github.io/mkdocs-material/blog/2021/09/13/search-better-faster-smaller/#rich-search-previews).

We've seen also that when using Elasticsearch with Highlighting, the html tags are not taken into account (html tags can be truncated in the search result highlight and highlighting segments conflicts with the html tags).

How are you handling the display of search results in Backstage ?

2024-07-10 06:49 UTC, alexef commented
@tcardonne atm I'm using a custom document collator in backstage, which I put in between the default one (that downloads search-index.json from s3) and I strip the tags before they are sent to Opensearch. So my index doesn't contain html tags, and the search results (with highlighting) work just like before.

In https://github.com/backstage/backstage/pull/25497 I'm preparing a less intrusive method that would allow minimal changes to the code, and allow us to continue to use the `DefaultTechDocsCollatorFactory` collator (by introducing the techdocs transformer, adding tags and stripping html in there).

2024-07-18 08:55 UTC, alexef commented
up

2024-08-01 18:22 UTC, merged