Update markdown >3.2 and graphviz extension
backstage/mkdocs-techdocs-core pull request #74
Opened 2022-07-27 18:42 UTC by iswariyam

## Summary:

* Update markdown_inline_graphviz_extension to 1.1.1 as errors related to svg rendering is fixed in this [PR](https://github.com/cesaremorel/markdown-inline-graphviz/pull/10)
* The latest version of markdown_inline_graphviz_extension is now compatible with markdown 3.3 and above

**Related to #37** 
**Fixes #36 and #45 (allows users to use markdown >=3.3)**

2022-07-27 19:00 UTC, iswariyam commented
@camilaibs @iamEAP  Could you please review and approve this? Merging this PR would allow folks to use other mkdocs plugins (like mkdocstrings) which only work with markdown >3.3 in conjunction with techdocs.

2022-07-28 13:21 UTC, camilaibs commented
> @camilaibs @iamEAP Could you please review and approve this? Merging this PR would allow folks to use other mkdocs plugins (like mkdocstrings) which only work with markdown >3.3 in conjunction with techdocs.

Starting to review 🙂

2022-07-29 07:42 UTC, camilaibs approved these changes
I followed these [steps](https://github.com/backstage/mkdocs-techdocs-core#testing-dependencies-end-to-end) for the integration test and everything went fine, thanks for contributing :tada:

2022-07-29 07:58 UTC, iswariyam commented
If this PR is merged, then changes would have to be made to techdocs [docs](https://github.com/backstage/backstage/blob/master/docs/features/techdocs/getting-started.md) (notes section at the end) and [techdocs-container](https://github.com/backstage/techdocs-container/blob/dd5b19ba867b72ffa75138d5f8268dc87b789756/Dockerfile#L23)

2022-07-29 08:13 UTC, camilaibs requested changes
@iswariyam I talked to @iamEAP and we're a little concerned about the open-endedness of the`markdown_inline_graphviz_extension` version constraint...
How about combining what we did with the `markdown` constraint >=1.1.1,<2 or something?

2022-07-29 08:25 UTC, iswariyam commented
> @iswariyam I talked to @iamEAP and we're a little concerned about the open-endedness of the`markdown_inline_graphviz_extension` version constraint... How about combining what we did with the `markdown` constraint >=1.1.1,<2 or something?

Fine by me. I'll push the change.

2022-07-29 09:25 UTC, iswariyam reviewed
Is there anything more needed for my side for this to be merged?

2022-07-29 09:29 UTC, camilaibs approved these changes
Thanks again for contributing 🙌🏻

2022-07-29 09:30 UTC, merged